=== Pheonix747hs/Webtech-pracs/prac3/employee.dtd
<!ELEMENT employees (Employee+)>
<!ELEMENT Employee (FirstName,LastName,Email)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== Pheonix747hs/Webtech-pracs/prac3/employee.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="styles.css"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<employees>
  <Employee>
    <FirstName>Alice</FirstName>
    <LastName>Johnson</LastName>
    <Email>alice.johnson@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>Benjamin</FirstName>
    <LastName>Miller</LastName>
    <Email>benjamin.miller@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>Chloe</FirstName>
    <LastName>Garcia</LastName>
    <Email>chloe.garcia@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>David</FirstName>
    <LastName>Wilson</LastName>
    <Email>david.wilson@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>Emily</FirstName>
    <LastName>Moore</LastName>
    <Email>emily.moore@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>William</FirstName>
    <LastName>Brown</LastName>
    <Email>william.brown@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>Sofia</FirstName>
    <LastName>Lewis</LastName>
    <Email>sofia.lewis@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>James</FirstName>
    <LastName>Clark</LastName>
    <Email>james.clark@example.com</Email>
  </Employee>
  
  <Employee>
    <FirstName>Isabella</FirstName>
    <LastName>Robinson</LastName>
    <Email>isabella.robinson@example.com</Email>
  </Employee>
</employees>
